# Generated by Django 4.2.30 on 2026-04-10 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourtHearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateTimeField()),
                ('court_name', models.CharField(max_length=200)),
                ('outcome', models.CharField(max_length=200)),
                ('presiding_judge', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YoungPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=10)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('caseworkers', models.ManyToManyField(blank=True, to='justice.caseworker')),
            ],
        ),
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offence_type', models.CharField(max_length=100)),
                ('date_of_offence', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('serious', 'Serious')], max_length=10)),
                ('description', models.TextField()),
                ('young_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offences', to='justice.youngperson')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('assigned_worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='justice.caseworker')),
                ('young_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='justice.youngperson')),
            ],
        ),
        migrations.CreateModel(
            name='HearingOffence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(max_length=100)),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justice.courthearing')),
                ('offence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justice.offence')),
            ],
        ),
        migrations.AddField(
            model_name='courthearing',
            name='offences',
            field=models.ManyToManyField(blank=True, through='justice.HearingOffence', to='justice.offence'),
        ),
        migrations.AddField(
            model_name='courthearing',
            name='young_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='justice.youngperson'),
        ),
    ]
